# Generated by Django 4.0.5 on 2022-08-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='gender',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
